name: Wf ZAP Full Scan
run-name: Runner ZAP Full Scan
on: 
  push:
    branches: [main, develop]
  workflow_dispatch:


jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: JOB-Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://testphp.vulnweb.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'